name: Java Ci with Maven

on: [push, pull_request]

jobs:
  run_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8

      - name: Run Test
        run: mvn -pl graphjet-core test -Dtest='com.twitter.graphjet.algorithms.salsa.SalsaTest#testSalsaWithRandomGraph'
                
  run_test_with_nondex:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 8
        
    - name: Run Test w nondex
      run: mvn -pl graphjet-core edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest='com.twitter.graphjet.algorithms.salsa.SalsaTest#testSalsaWithRandomGraph'
      
